### PR TITLE
Adding a folder for photos

### PR DESCRIPTION
**Pull request by MMikhailova**
### General Checks

- [x] the branch is up to date with `main`/`master`
- [x] the code works when pulled and run locally
- [x] All CI checks pass
- [x] all conflicts are resolved (if any)
- [x] PR has a descriptive title
- [x] PR has appropriate labels and milestones for easy identification
- [x] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [x] It is in the appropriate column in the project board (if necessary)
- [x] has short and clear description
- [x] is linked to an issue (if it is related)
- [x] feedback is addressed (if any and if it is appropriate feedback.)

## Markdown

- [x] the markdown source is formatted
- [x] spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [x] all links and images work

### CODE REVIEW

**Review by bermarte — CHANGES_REQUESTED** [review]
You can delete the .DS_Store file, I suggest to add a single file and not everything using 
`git add .`
You can create another commit, but better to remove the file using git:
`git rm .DS_Store`
Don't forget to to always a `git status` to see what you will add to the repo.

**Review by bermarte — APPROVED** [review]

**Comment by bermarte** [comment]
It's ok but I don't have access to the repo as administrator.

**Comment by MMikhailova** [comment]
@bermarte thank you, I try to use 'git status' every time I make a change. 
In case of DS_Store I didn't know what it was and wether I should add it as well to repo.

**Comment by bermarte** [comment]
The .`DS_Store` is an hidden file automatically created by Apple every time you open a folder with the Finder.

**Comment by bermarte** [comment]
The best thing to get rid of the various DS_Store files, would be to add
`**/.DS_Store` to your `.gitignore` file.
The 2 asterisks will recursively search within all directories of your repository.

**Pull request merged**
